import './globals.css'
import { cn } from '~/lib/utils'
import type { Metadata } from 'next'
import { McLaren } from 'next/font/google'
import { Header } from '~/components/header'
import { Footer } from '~/components/footer'
import { TipDialogs } from '~/components/tip-dialogs'
import { Providers } from './provider'

const mcLaren = McLaren({
  variable: '--font-mclaren',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(mcLaren.variable, 'antialiased')}>
        <Providers
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange={false}
        >
          <main className="gap-2 overflow-x-hidden font-sans">
            <Header />
            {children}
            <TipDialogs />
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  )
}
